name: "nav_localization"
version: "0.1.0"
description: "Navigation localization powered by ScanContext"
maintainers:
  - name: "fins"
    email: "fins@sjtu.edu.cn"
depends:
  PCL: "system"
  OpenCV: "system"

  nav_msgs: "system"
  geometry_msgs: "system"
  cv_bridge: "system"
  pcl_conversions: "system"
  
  small_gicp: "1.0.0"
recipes:
  small_gicp:
    git: "https://github.com/koide3/small_gicp.git"
    build_system: "cmake"
    versions:
      "1.0.0":
        tag: "v1.0.0"
licenses:
  - "MIT"